services:
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./web:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
