services:
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./web:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./api/app:/code/app
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/postgres
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    volumes:
      - db_data:/var/lib/postgresql/data  # ← 永続化ポイント
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db_data:
